version: 2.1
setup: true

orbs:
  orb-tools: circleci/orb-tools@10.0
  continuation: circleci/continuation@1.0.0

jobs:
  trigger-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/test-deploy.yml

workflows:
  test-publish:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          persist-to-workspace: true
      - orb-tools/publish-dev:
          orb-name: lucos/deploy
          context: orb-publishing
          attach-workspace: true
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - trigger-tests:
          requires:
            - orb-tools/publish-dev
